name: Fetch Telegram Messages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  

      - uses: actions/setup-python@v5   # setup-python v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - name: Run fetch script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE: ${{ secrets.PHONE }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: python fetch_messages.py

      - name: Upload encrypted database
        uses: actions/upload-artifact@v4   #v3 to v4
        with:
          name: telegram-db-encrypted
          path: messages.db.encrypted
          retention-days: 30
